### PR TITLE
Update rand and quickcheck dependencies

### LINKED ISSUE #60: Manually update dependabot's recommendations
Dependabot has a couple PRs open to update some of this project's dependencies but it looks like updating is going to take a bit of manual work, i.e. updating the symbols that changed / went away.

### PR DESCRIPTION
**Pull request by lionel1704**
This PR includes the commits automatically created by @dependabot along with the fixes needed for the dependency version updates.

Resolves #60 
Supersedes #58 and #59

### CODE REVIEW

**Comment by shnewto** [comment]
🤔 these failures look like they're coming from cargo-travis, the crate we're using for test coverage reports... I've been thinking abt migrating the logic in that `.travis.yml` to use tarpaulin instead, looks like that'll need to happen first 🤔 

I can prob hop into that in the next few days, I imagine it'll end up looking a lot like the setup here https://github.com/shnewto/ttaw/blob/master/.travis.yml

**Comment by shnewto** [comment]
@lionel1704 I merged some changes to the CI script that will hopefully address the failures on this PR. Would you mind syncing / updating your branch so we can make sure that did the trick?

**Comment by lionel1704** [comment]
That's rebased and updated :+1: CI looks happy :tada:

**Comment by shnewto** [comment]
Awesome! Thank you!!

**Pull request merged**
