### PR TITLE
LLVM coverage reporting

### PR DESCRIPTION
**Pull request by CrockAgile**
I saw a repo the other day using LLVM to inject coverage reporting. I thought I would give it a try since `grcov` having issues.

### CODE REVIEW

**Comment by shnewto** [comment]
🤩

**Comment by CrockAgile** [comment]
maybe a solution for #130 ? idk!

**Comment by shnewto** [comment]
toootally, I think it's an awesome solution to #130

**Comment by CrockAgile** [comment]
cool then im gonna go for it. no time like the present 🏃‍♂️

**Comment by shnewto** [comment]
🎉

**Pull request merged**
