### PR TITLE
Update to Rust edition 2021

### PR DESCRIPTION
**Pull request by CrockAgile**
# Changes

This attempts a non-breaking change of updating BNF's Rust edition ([read more about editions](https://doc.rust-lang.org/edition-guide/editions/index.html)).

The quick summary of editions is:
* Release a feature that would otherwise be backwards incompatible, we do so as part of a new Rust edition
* Editions are opt-in, and so existing crates do not see these changes until they explicitly migrate over to the new edition
* Editions do not split the ecosystem

The current edition used by BNF is Rust 2015, which is the default. But it is good practice to upgrade crates when possible, because it unlocks future language features.

For example, one improvement made in Rust 2018 edition was the removal of redundant `extern crate` uses.

```rust
// rust 2015
extern crate rand;

use rand::thread_rng;

// rust 2018
use rand::thread_rng;
``` 

# Issues

I don't know if this is a new issue from these changes, or running tests on new hardware, but I did encounter one flaky test:

```rust
fn recursion_limit() {
  let grammar: Result<Grammar, _> = "<nonterm> ::= <nonterm>".parse();
  assert!(grammar.is_ok(), "{:?} should be ok", grammar);
  let sentence = grammar.unwrap().generate();
  assert!(sentence.is_err(), "{:?} should be err", sentence);
  match sentence {
      Err(e) => match e {
          Error::RecursionLimit(_) => (),
          e => panic!("should should be Error::RecursionLimit: {:?}", e),
      },
      Ok(s) => panic!("should should be Error::RecursionLimit: {}", s),
  }
}
```

This test would fail sometimes, and pass others. 🤷‍♂️

### CODE REVIEW

**Comment by shnewto** [comment]
I can revisit that recursion limit test, the whole method of "maybe too much recursion to monitor the stack and bail if we need to" logic is something I've been daydreaming about fixing since i implemented it 😅 . But don't think reimplementing that needs to be a blocker for this. The only thing I'd like to be somewhat confident about is that using the generate logic isn't also flakey now / can cause panics

**Comment by CrockAgile** [comment]
> The only thing I'd like to be somewhat confident about is that using the generate logic isn't also flakey now / can cause panics

anything beyond running the tests I could do to get that confidence? seems to have passed on all platforms in CI, but I got a few stack explosion panics running locally

**Comment by shnewto** [comment]
Ah thanks for that effort! I kinda want to poke at it and see if I can reproduce on my end, so far I haven't seen it 🤔 Don't sweat me waiting on anything from you though, these updates are awesome. It's on me now, I'll try not to let this linger too much longer before making a call on the panic thing 🙏

**Review by shnewto — APPROVED** [review]

**Review by shnewto — APPROVED** [review]
👍👍 thanks!

**Pull request merged**
